export const SHOW_SIGNIN_MODAL = 'SHOW_SIGNIN_MODAL'
export const HIDE_SIGNIN_MODAL = 'HIDE_SIGNIN_MODAL'
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL'
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL'

export const SHOW_MOBILE_MENU = 'SHOW_MOBILE_MENU'
export const HIDE_MOBILE_MENU = 'HIDE_MOBILE_MENU'

export const SHOW_COUPON_MENU = 'SHOW_COUPON_MENU'
export const HIDE_COUPON_MENU = 'HIDE_COUPON_MENU'